feat: updated the check versions action

diff --git a/.github/workflows/check_versions.yml b/.github/workflows/check_versions.yml
--- a/.github/workflows/check_versions.yml
+++ b/.github/workflows/check_versions.yml
@@ -13,5 +13,20 @@ jobs:
       - name: Compare versions in the repository
         run: |
           git fetch origin master
-          VERSION=$(git show FETCH_HEAD:VERSION)
-          echo $VERSION
+          MASTER_VERSION=$(git show FETCH_HEAD:VERSION)
+          CURRENT_VERSION=$(cat VERSION)
+
+          if [[ "$MASTER_VERSION" == "$CURRENT_VERSION" ]];  then
+              echo "Current version is the same as master, invalid"
+              exit 1
+          fi
+
+          HIGHEST_VALUE=$(echo -e "$MASTER_VERSION\n$CURRENT_VERSION" | sort -rV | head -1)
+
+          if [[ "$HIGHEST_VALUE" == "$CURRENT_VERSION" ]]; then
+              echo "Thanks for bumping"
+              exit 0
+          else
+              echo "You didn't bump"
+              exit 1
+          fi
